# HOMEWORK 1

In [1]:
import numpy as np
import os
import pandas as pd

## Question 1

In [2]:


np.__version__

'1.20.3'

In [3]:
df = pd.read_csv("homework1.csv")

In [4]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [5]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [6]:
string_list = list(df.dtypes[df.dtypes == "object"].index)
string_list

['make',
 'model',
 'engine_fuel_type',
 'transmission_type',
 'driven_wheels',
 'market_category',
 'vehicle_size',
 'vehicle_style']

In [7]:
for col in string_list:
    df[col] = df[col].str.lower().str.replace(" ", "_")

## Question 2

In [8]:
##Question 2
df.shape[0]

11914

## Question 3

In [9]:
## Question 3
df.make.value_counts().head(3)

chevrolet     1123
ford           881
volkswagen     809
Name: make, dtype: int64

## Question 4

In [10]:
## Question 4
df[df.make == "audi"].model.nunique()

34

## Question 5

In [11]:
## Question 5
len(df.columns[df.isnull().any()])

5

In [12]:
df.isnull().sum()

make                    0
model                   0
year                    0
engine_fuel_type        3
engine_hp              69
engine_cylinders       30
transmission_type       0
driven_wheels           0
number_of_doors         6
market_category      3742
vehicle_size            0
vehicle_style           0
highway_mpg             0
city_mpg                0
popularity              0
msrp                    0
dtype: int64

## Question 6

In [13]:
list(df.columns[df.isnull().any()])

['engine_fuel_type',
 'engine_hp',
 'engine_cylinders',
 'number_of_doors',
 'market_category']

In [14]:
df.engine_cylinders.median()

6.0

In [15]:
df.engine_cylinders.mode()

0    4.0
Name: engine_cylinders, dtype: float64

In [16]:
## filling na in engine_cylinders column
df["engine_cylinders"] = df["engine_cylinders"].fillna(0)

In [17]:
df["engine_cylinders"].median()

6.0

In [18]:
df["engine_cylinders"].mode()

0    4.0
Name: engine_cylinders, dtype: float64

## Question 7

In [19]:
## ALl Lotus cars
lotus= df[df.make == "lotus"]

In [20]:
lotus.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29 entries, 3912 to 4297
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   make               29 non-null     object 
 1   model              29 non-null     object 
 2   year               29 non-null     int64  
 3   engine_fuel_type   29 non-null     object 
 4   engine_hp          29 non-null     float64
 5   engine_cylinders   29 non-null     float64
 6   transmission_type  29 non-null     object 
 7   driven_wheels      29 non-null     object 
 8   number_of_doors    29 non-null     float64
 9   market_category    29 non-null     object 
 10  vehicle_size       29 non-null     object 
 11  vehicle_style      29 non-null     object 
 12  highway_mpg        29 non-null     int64  
 13  city_mpg           29 non-null     int64  
 14  popularity         29 non-null     int64  
 15  msrp               29 non-null     int64  
dtypes: float64(3), int64(5)

In [21]:
## selecting specific columns - engine_hp and engine_cylinders
lotus_df = lotus[["engine_hp", "engine_cylinders"]]

In [22]:
lotus_df = lotus_df.drop_duplicates()

In [23]:
X = np.array(lotus_df)

X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [24]:
XTX = X.T.dot(X)

XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [25]:
XTX_inv = np.linalg.inv(XTX)

XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [26]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [27]:
w = XTX_inv.dot(X.T).dot(y)

w

array([  4.59494481, -63.56432501])